/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.ClsCandidato;
import Clases.ClsVotante;
import Clases.ClsMensaje;
import Clases.ClsVotarCandidato;
import Controladores.CtlCandidato;
import Controladores.CtlVotante;
import Controladores.CtlVotarCandidato;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FrmVotarCandidato extends javax.swing.JFrame {

    JFrame frameMenu;
    CtlCandidato controladorCandidato;
    LinkedList<ClsCandidato> candidatos;
    
    CtlVotante controladorVotante;
    LinkedList<ClsVotante> votantes;

    CtlVotarCandidato controladorVotos;
    LinkedList<ClsVotarCandidato> votos;

    
    /**
     * Creates new form FrmMenu
     */
    public FrmVotarCandidato(JFrame frameMenu) {
        initComponents();
        this.frameMenu = frameMenu;
        this.controladorCandidato = new CtlCandidato();
        ObtenerCandidatos();
        
        this.controladorVotante = new CtlVotante();
        ObtenerVotantes();
      
        
        this.controladorVotos =new CtlVotarCandidato();
        ObtenerVotos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVotarCandidatos = new javax.swing.JTable();
        botonVotar = new javax.swing.JButton();
        campoDocumento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione el candidato por el que desea votar");

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        tablaVotarCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Documento", "Nombre", "Partido"
            }
        ));
        jScrollPane2.setViewportView(tablaVotarCandidatos);

        botonVotar.setText("VOTAR");
        botonVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVotarActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese su Documento");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("VOTACIONES ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(botonVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(botonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(botonVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.setVisible(false);
        this.frameMenu.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVotarActionPerformed
       
        String idVotante = campoDocumento.getText();

       
        int columna = 0;
        int fila = this.tablaVotarCandidatos.getSelectedRow();

        String idCandidato = this.tablaVotarCandidatos.getModel().getValueAt(fila, columna).toString();

        
        
        ClsCandidato candidato = this.BuscarCandidato(idCandidato);
        ClsVotante votante =this.BuscarVotante(idVotante);
        
        if ( votante != null){

        ClsVotarCandidato voto =new ClsVotarCandidato(idCandidato, idVotante);


         ClsMensaje mensaje = this.controladorVotos.agregarVoto(voto);
         
                 
                  
         if (mensaje.getTipo().equals(ClsMensaje.OK)) {

             ObtenerVotos();
             
        }

        JOptionPane.showMessageDialog(rootPane, mensaje.getTexto()); 
         
         
        } else {
        JOptionPane.showInternalMessageDialog(null, "El votante no ha esta registrado");

        
        }
        
        
               
        //JOptionPane.showInternalMessageDialog(null, candidato.getNumeroDocumento());
        
        

       

        
        
        
    }//GEN-LAST:event_botonVotarActionPerformed

    public void ObtenerVotos() {

        this.votos = this.controladorVotos.ObtenerVotos();

    }
    
    
    
    public void ObtenerCandidatos() {

        this.candidatos = this.controladorCandidato.Obtenercandidatos();
        this.ActualizarTabla(candidatos);

    }

    public ClsCandidato BuscarCandidato(String idCandidato) {

        for (ClsCandidato candidato : this.candidatos) {

            if (candidato.getNumeroDocumento().equals(idCandidato)) {

                return candidato;
            }

        }

        return null;

    }
    
        public void ObtenerVotantes() {

        this.votantes = this.controladorVotante.Obtenervotante();
        
    }
    
    
    public ClsVotante BuscarVotante(String idVotante) {

        for (ClsVotante votante : this.votantes) {

            if (votante.getNumeroDocumento().equals(idVotante)) {

                return votante;
            }

        }

        return null;

    }


    private void ActualizarTabla(LinkedList<ClsCandidato> lista) {

        DefaultTableModel modelo = (DefaultTableModel) tablaVotarCandidatos.getModel();
        modelo.setRowCount(0);

        for (ClsCandidato c : lista) {

            Object[] fila = {c.getNumeroDocumento(),c.getNombre(),
                c.getPartidoPolitico(),};

            modelo.addRow(fila);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVotarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVotarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVotarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVotarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVotarCandidato(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton botonVotar;
    private javax.swing.JTextField campoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaVotarCandidatos;
    // End of variables declaration//GEN-END:variables
}
